dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.14.x

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -cover ./pkg/...